-- CREATE TABLE IF NOT EXISTS users (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     role VARCHAR(255), CHOICES('user', 'admin'), DEFAULT 'user' NOT NULL,
--     createdAt TIMESTAMP DEFAULT NOW()
-- );